### ISSUE TITLE
Refactoring the server-client logic with OOP

### ISSUE THREAD

**Issue by nikita-kotsehub** [globus-labs/FLoX#23]
Implementing the client-server logic according to the draft in PR #22

**Comment by nikita-kotsehub** [comment]
Got stuck with an indentation & deserialization issue when submitting class methods build on top of ABC (Abstract Base Class) to funcX. Here is a minimum viable code that reproduces the error: 
```
!pip install funcx
!pip install funcx-endpoint
!funcx-endpoint configure ep1
!funcx-endpoint start ep1
```

```
from abc import ABC, abstractmethod
from funcx import FuncXExecutor

ep1 = "your-endpoint-uuid"

class MyAbstractClass(ABC):
    @abstractmethod
    def greeting(self):
        pass

    @abstractmethod
    def farewell(self):
        pass

class CustomClass(MyAbstractClass):
    def __init__(self):
        self.var = "CLASS VARIABLE"
    
    def greeting(self):
        return "Hello, world"
        
    def farewell(self):
        return "Bye, world!"

ClassInstance = CustomClass()

with FuncXExecutor(endpoint_id=ep1) as fx:
    task = fx.submit(ClassInstance.greeting)

print(task.result())
```

Running this produces the following error:

```
---------------------------------------------------------------------------
FuncxTaskExecutionFailed                  Traceback (most recent call last)
[<ipython-input-9-c11343ffc4b7>](https://localhost:8080/#) in <module>
     26     task = fx.submit(ClassInstance.greeting)
     27 
---> 28 print(task.result())

1 frames
[/usr/lib/python3.7/concurrent/futures/_base.py](https://localhost:8080/#) in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

FuncxTaskExecutionFailed: 
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/funcx/serialize/facade.py", line 116, in unpack_and_deserialize
        deserialized = self.deserialize(current)
      File "/usr/local/lib/python3.7/dist-packages/funcx/serialize/facade.py", line 67, in deserialize
        result = self.methods_for_code[header].deserialize(payload)
      File "/usr/local/lib/python3.7/dist-packages/funcx/serialize/concretes.py", line 87, in deserialize
        exec(body)
      File "<string>", line 1
        def greeting(self):
        ^
    IndentationError: unexpected indent
```

**Comment by nikita-kotsehub** [comment]
Ran into another issue when working with ABCs and funcX: funcX gives a pickle error when I try to submit an ABC-based Class instance to funcX as a variable. Here is code to reproduce the error. Don't forget to create an endpoint_id.

**Note**: As soon as I remove dependency on the ABC class from both Class definitions, the code runs fine. 

**Code:**
```
from abc import ABC, abstractmethod
from funcx import FuncXExecutor

ep1 = "your-endpoint-uuid"

class TrainerABC(ABC):
    @abstractmethod
    def fit():
      pass

    def evaluate():
      pass

class CustomTrainer(TrainerABC):
    def fit(self):
        return "Fitted the model!"

    def evaluate(self):
        return "Evaluated the model"


class MyAbstractClass(ABC):
    @abstractmethod
    def greeting(self):
        pass

    @abstractmethod
    def farewell(self):
        pass

class CustomClass(MyAbstractClass):
    def __init__(self):
        self.var = "CLASS VARIABLE"
    
    def greeting(self, ModelTrainer):
        return f"Hello, world! {ModelTrainer.fit()}"
        
    def farewell(self):
        return "Bye, world!"

ClassInstance = CustomClass()
TrainerInstance = CustomTrainer()

with FuncXExecutor(endpoint_id=ep1) as fx:
    task = fx.submit(ClassInstance.greeting, ModelTrainer=TrainerInstance)

print(task.result())
```

**Error**
```
Exception in thread Thread-32:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/funcx/sdk/executor.py", line 567, in _task_submitter_impl
    self._submit_tasks(futs, tasks)
  File "/usr/local/lib/python3.7/dist-packages/funcx/sdk/executor.py", line 645, in _submit_tasks
    batch.add(task.function_id, task.endpoint_id, task.args, task.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/funcx/sdk/batch.py", line 53, in add
    ser_kwargs = self.fx_serializer.serialize(kwargs)
  File "/usr/local/lib/python3.7/dist-packages/funcx/serialize/facade.py", line 53, in serialize
    raise last_exception
  File "/usr/local/lib/python3.7/dist-packages/funcx/serialize/facade.py", line 41, in serialize
    serialized = method.serialize(data)
  File "/usr/local/lib/python3.7/dist-packages/funcx/serialize/concretes.py", line 24, in serialize
    x = codecs.encode(dill.dumps(data), "base64").decode()
  File "/usr/local/lib/python3.7/dist-packages/dill/_dill.py", line 364, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "/usr/local/lib/python3.7/dist-packages/dill/_dill.py", line 336, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/usr/local/lib/python3.7/dist-packages/dill/_dill.py", line 620, in dump
    StockPickler.dump(self, obj)
  File "/usr/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.7/dist-packages/dill/_dill.py", line 1251, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 890, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 633, in save_reduce
    save(cls)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.7/dist-packages/dill/_dill.py", line 1840, in save_type
    )), obj=obj, postproc_list=postproc_list)
  File "/usr/local/lib/python3.7/dist-packages/dill/_dill.py", line 1140, in _save_with_postproc
    pickler.save_reduce(*reduction, obj=obj)
  File "/usr/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 789, in save_tuple
    save(element)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 774, in save_tuple
    save(element)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.7/dist-packages/dill/_dill.py", line 1840, in save_type
    )), obj=obj, postproc_list=postproc_list)
  File "/usr/local/lib/python3.7/dist-packages/dill/_dill.py", line 1140, in _save_with_postproc
    pickler.save_reduce(*reduction, obj=obj)
  File "/usr/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 789, in save_tuple
    save(element)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.7/dist-packages/dill/_dill.py", line 1251, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 524, in save
    rv = reduce(self.proto)
TypeError: can't pickle _abc_data objects

---------------------------------------------------------------------------
CancelledError                            Traceback (most recent call last)
[<ipython-input-28-4b2aa5ce2f1f>](https://localhost:8080/#) in <module>
     42     task = fx.submit(ClassInstance.greeting, ModelTrainer=TrainerInstance)
     43 
---> 44 print(task.result())

[/usr/lib/python3.7/concurrent/futures/_base.py](https://localhost:8080/#) in result(self, timeout)
    424         with self._condition:
    425             if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:
--> 426                 raise CancelledError()
    427             elif self._state == FINISHED:
    428                 return self.__get_result()

CancelledError:
```

**Comment by nikita-kotsehub** [comment]
So far I've implemented an OOP version of the flox code and tested it in the attached Google Colab Notebook. However, I had to remove dependencies on ABC classes due to the errors above. The code is also present in [basic-oop-flow branch](https://github.com/globus-labs/FLoX/tree/basic-oop-flows). The notebook version works but needs to be tested with real devices too: [https://colab.research.google.com/drive/17JuDesxlGbv1z3RQvQZu2cSOMtUoLMF_?usp=sharing](https://colab.research.google.com/drive/17JuDesxlGbv1z3RQvQZu2cSOMtUoLMF_?usp=sharing)
